ALTER TABLE users ADD (profile_image CLOB);

CREATE TABLE user_notifications (
  notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  title VARCHAR2(160) NOT NULL,
  message VARCHAR2(1000) NOT NULL,
  type VARCHAR2(30) DEFAULT 'info' NOT NULL,
  is_read CHAR(1) DEFAULT 'N' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT user_notifications_read_ck CHECK (is_read IN ('Y', 'N'))
);

CREATE INDEX user_notifications_user_ix ON user_notifications(user_id, is_read, created_at);
