-- Normalize emergency management to 1NF, 2NF, 3NF, and 4NF.
-- Run after migrate_emergency_management.sql. This migration preserves existing cases.

-- 1. Normalize the multi-valued TAGS and repeated consent attributes.
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE EMERGENCY_CASE_TAGS (
      EMERGENCY_ID NUMBER NOT NULL REFERENCES EMERGENCY_CASES(EMERGENCY_ID) ON DELETE CASCADE,
      TAG VARCHAR2(80) NOT NULL,
      CONSTRAINT EMERGENCY_CASE_TAGS_PK PRIMARY KEY (EMERGENCY_ID, TAG)
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE EMERGENCY_CASE_CONSENTS (
      EMERGENCY_ID NUMBER NOT NULL REFERENCES EMERGENCY_CASES(EMERGENCY_ID) ON DELETE CASCADE,
      CONSENT_TYPE VARCHAR2(30) NOT NULL,
      IS_APPROVED NUMBER(1) DEFAULT 0 NOT NULL,
      RECORDED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT EMERGENCY_CASE_CONSENTS_PK PRIMARY KEY (EMERGENCY_ID, CONSENT_TYPE),
      CONSTRAINT EMERGENCY_CASE_CONSENTS_TYPE_CK CHECK (CONSENT_TYPE IN (''CPR'', ''ESTIMATE'', ''DEPOSIT'')),
      CONSTRAINT EMERGENCY_CASE_CONSENTS_APPROVED_CK CHECK (IS_APPROVED IN (0, 1))
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. Every emergency case must reference a patient. Create a patient for legacy
--    rows that have not yet been linked, retaining their recorded details.
DECLARE
  v_patient_id PATIENTS.PATIENT_ID%TYPE;
BEGIN
  FOR r IN (SELECT * FROM EMERGENCY_CASES WHERE PATIENT_ID IS NULL) LOOP
    INSERT INTO PATIENTS (PET_NAME, PET_SPECIES, PET_BREED, PET_AGE, OWNER_NAME, OWNER_PHONE)
    VALUES (
      NVL(r.PATIENT_NAME, 'Emergency Patient'),
      NVL(r.SPECIES, 'Unknown'),
      r.BREED,
      r.AGE,
      NVL(r.OWNER_NAME, 'Emergency Contact'),
      r.OWNER_PHONE
    )
    RETURNING PATIENT_ID INTO v_patient_id;

    UPDATE EMERGENCY_CASES SET PATIENT_ID = v_patient_id WHERE EMERGENCY_ID = r.EMERGENCY_ID;
  END LOOP;
END;
/

-- 3. Migrate tags and consent values before removing the denormalized columns.
DECLARE
  v_tag VARCHAR2(80);
BEGIN
  FOR r IN (SELECT EMERGENCY_ID, TAGS, CPR_APPROVED, ESTIMATE_SIGNED, DEPOSIT_PAID FROM EMERGENCY_CASES) LOOP
    FOR n IN 1 .. REGEXP_COUNT(NVL(r.TAGS, ''), '[^,\[\]"]+') LOOP
      v_tag := TRIM(REGEXP_SUBSTR(r.TAGS, '[^,\[\]"]+', 1, n));
      IF v_tag IS NOT NULL THEN
        BEGIN
          INSERT INTO EMERGENCY_CASE_TAGS (EMERGENCY_ID, TAG) VALUES (r.EMERGENCY_ID, v_tag);
        EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
        END;
      END IF;
    END LOOP;

    MERGE INTO EMERGENCY_CASE_CONSENTS c USING (SELECT r.EMERGENCY_ID id, 'CPR' type, NVL(r.CPR_APPROVED, 1) approved FROM DUAL) s
      ON (c.EMERGENCY_ID = s.id AND c.CONSENT_TYPE = s.type)
      WHEN NOT MATCHED THEN INSERT (EMERGENCY_ID, CONSENT_TYPE, IS_APPROVED) VALUES (s.id, s.type, s.approved);
    MERGE INTO EMERGENCY_CASE_CONSENTS c USING (SELECT r.EMERGENCY_ID id, 'ESTIMATE' type, NVL(r.ESTIMATE_SIGNED, 0) approved FROM DUAL) s
      ON (c.EMERGENCY_ID = s.id AND c.CONSENT_TYPE = s.type)
      WHEN NOT MATCHED THEN INSERT (EMERGENCY_ID, CONSENT_TYPE, IS_APPROVED) VALUES (s.id, s.type, s.approved);
    MERGE INTO EMERGENCY_CASE_CONSENTS c USING (SELECT r.EMERGENCY_ID id, 'DEPOSIT' type, NVL(r.DEPOSIT_PAID, 0) approved FROM DUAL) s
      ON (c.EMERGENCY_ID = s.id AND c.CONSENT_TYPE = s.type)
      WHEN NOT MATCHED THEN INSERT (EMERGENCY_ID, CONSENT_TYPE, IS_APPROVED) VALUES (s.id, s.type, s.approved);
  END LOOP;
END;
/

ALTER TABLE EMERGENCY_CASES MODIFY (PATIENT_ID NOT NULL);

-- 4. Remove values derivable from PATIENTS, EMERGENCY_CAGES, STAFF/USERS,
--    EMERGENCY_CASE_TAGS, and EMERGENCY_CASE_CONSENTS.
DECLARE
  PROCEDURE drop_column(p_column VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMERGENCY_CASES DROP COLUMN ' || p_column;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -904 THEN RAISE; END IF;
  END;
BEGIN
  drop_column('PATIENT_NAME');
  drop_column('SPECIES');
  drop_column('BREED');
  drop_column('AGE');
  drop_column('WEIGHT');
  drop_column('OWNER_NAME');
  drop_column('OWNER_PHONE');
  drop_column('CAGE_ID');
  drop_column('ASSIGNED_VET_NAME');
  drop_column('TAGS');
  drop_column('CPR_APPROVED');
  drop_column('ESTIMATE_SIGNED');
  drop_column('DEPOSIT_PAID');
END;
/

CREATE INDEX EMERGENCY_CASE_TAGS_TAG_IX ON EMERGENCY_CASE_TAGS(TAG);
CREATE INDEX EMERGENCY_CASE_CONSENTS_CASE_IX ON EMERGENCY_CASE_CONSENTS(EMERGENCY_ID);
