-- ============================================
-- STAFF_MESSAGES TABLE
-- Internal clinic communications & medical attachments
-- ============================================

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'STAFF_MESSAGES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE staff_messages (
        message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sender_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
        receiver_id NUMBER REFERENCES users(user_id) ON DELETE CASCADE,
        message_text CLOB,
        attachment_data CLOB,
        attachment_name VARCHAR2(255),
        attachment_type VARCHAR2(100),
        attachment_size NUMBER,
        is_read NUMBER(1) DEFAULT 0 NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    ';
  END IF;
END;
/

-- Indexes for fast conversation lookup and sorting
DECLARE
  PROCEDURE add_idx(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = UPPER(p_name);
    IF v_cnt = 0 THEN
      BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX ' || p_name || ' ON ' || p_sql;
      EXCEPTION WHEN OTHERS THEN NULL;
      END;
    END IF;
  END;
BEGIN
  add_idx('IDX_STAFF_MSG_SENDER', 'staff_messages(sender_id)');
  add_idx('IDX_STAFF_MSG_RECEIVER', 'staff_messages(receiver_id)');
  add_idx('IDX_STAFF_MSG_CREATED', 'staff_messages(created_at)');
END;
/

COMMIT;
