CREATE TABLE doctor_availability (
  availability_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id NUMBER NOT NULL UNIQUE REFERENCES staff(staff_id),
  availability_status VARCHAR2(20) DEFAULT 'Available' NOT NULL,
  start_time VARCHAR2(5),
  end_time VARCHAR2(5),
  leave_reason VARCHAR2(255),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT doctor_availability_status_ck
    CHECK (availability_status IN ('Available', 'Unavailable', 'On Leave'))
);

COMMIT;
