-- Migration: Normalize Patient Age into Integer Value and Unit Dropdown
-- File: pet_clinic_backend/database/migrate_patient_age_normalization.sql

-- 1. Add atomic columns to PATIENTS
ALTER TABLE PATIENTS ADD (
  PET_AGE_VALUE NUMBER(3),
  PET_AGE_UNIT VARCHAR2(10)
);

-- 2. Add atomic columns to APPOINTMENTS
ALTER TABLE APPOINTMENTS ADD (
  PET_AGE_VALUE NUMBER(3),
  PET_AGE_UNIT VARCHAR2(10)
);

-- 3. Populate existing PATIENTS data
UPDATE PATIENTS
SET PET_AGE_VALUE = TO_NUMBER(REGEXP_SUBSTR(PET_AGE, '^[0-9]+')),
    PET_AGE_UNIT = NVL(TRIM(LOWER(REGEXP_SUBSTR(PET_AGE, '[a-zA-Z]+'))), 'years')
WHERE PET_AGE IS NOT NULL AND REGEXP_LIKE(PET_AGE, '^[0-9]+');

UPDATE PATIENTS
SET PET_AGE_VALUE = 3, PET_AGE_UNIT = 'years'
WHERE PET_AGE_VALUE IS NULL AND LOWER(PET_AGE) LIKE '%adult%';

-- 4. Populate existing APPOINTMENTS data
UPDATE APPOINTMENTS
SET PET_AGE_VALUE = TO_NUMBER(REGEXP_SUBSTR(PET_AGE, '^[0-9]+')),
    PET_AGE_UNIT = NVL(TRIM(LOWER(REGEXP_SUBSTR(PET_AGE, '[a-zA-Z]+'))), 'years')
WHERE PET_AGE IS NOT NULL AND REGEXP_LIKE(PET_AGE, '^[0-9]+');

UPDATE APPOINTMENTS
SET PET_AGE_VALUE = 3, PET_AGE_UNIT = 'years'
WHERE PET_AGE_VALUE IS NULL AND LOWER(PET_AGE) LIKE '%adult%';

COMMIT;
