-- Migration: Ensure USER_NOTIFICATIONS table and columns exist
-- Run as application schema owner.

DECLARE
  v_count NUMBER;
BEGIN
  -- 1. Create table if missing
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'USER_NOTIFICATIONS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE user_notifications (
        notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
        title VARCHAR2(160) NOT NULL,
        message VARCHAR2(1000) NOT NULL,
        type VARCHAR2(30) DEFAULT ''info'' NOT NULL,
        link VARCHAR2(255),
        source_id VARCHAR2(100),
        is_read CHAR(1) DEFAULT ''N'' NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT user_notifications_read_ck CHECK (is_read IN (''Y'', ''N''))
      )
    ';
  END IF;

  -- 2. Add link column if missing
  SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'USER_NOTIFICATIONS' AND column_name = 'LINK';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE user_notifications ADD (link VARCHAR2(255))';
  END IF;

  -- 3. Add source_id column if missing
  SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'USER_NOTIFICATIONS' AND column_name = 'SOURCE_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE user_notifications ADD (source_id VARCHAR2(100))';
  END IF;
END;
/

-- Indexes for performance
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX user_notif_user_read_ix ON user_notifications(user_id, is_read, created_at)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX user_notif_source_ix ON user_notifications(user_id, source_id)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;
