-- ============================================================
-- MIGRATE EMERGENCY MANAGEMENT
-- Enhances EMERGENCY_CASES and creates tables for:
-- 1. EMERGENCY_CAGES (ICU/Iso/General bed management)
-- 2. EMERGENCY_FLOWSHEET (Hourly vitals/fluids/meds monitoring)
-- 3. EMERGENCY_STAT_ORDERS (Emergency stat orders & completion)
-- ============================================================

-- 1. Add new columns to EMERGENCY_CASES if they don't already exist
DECLARE
  v_count NUMBER;
  PROCEDURE add_col(p_table VARCHAR2, p_col VARCHAR2, p_def VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = UPPER(p_table) AND column_name = UPPER(p_col);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_col || ' ' || p_def || ')';
    END IF;
  END;
BEGIN
  add_col('EMERGENCY_CASES', 'SPECIES', 'VARCHAR2(50) DEFAULT ''Dog''');
  add_col('EMERGENCY_CASES', 'BREED', 'VARCHAR2(100) DEFAULT ''Mixed Breed''');
  add_col('EMERGENCY_CASES', 'AGE', 'VARCHAR2(50) DEFAULT ''Adult''');
  add_col('EMERGENCY_CASES', 'WEIGHT', 'NUMBER DEFAULT 10');
  add_col('EMERGENCY_CASES', 'OWNER_PHONE', 'VARCHAR2(50)');
  add_col('EMERGENCY_CASES', 'SOURCE', 'VARCHAR2(30) DEFAULT ''website''');
  add_col('EMERGENCY_CASES', 'AI_REASONING', 'CLOB');
  add_col('EMERGENCY_CASES', 'TAGS', 'VARCHAR2(255) DEFAULT ''[]''');
  add_col('EMERGENCY_CASES', 'CAGE_ID', 'VARCHAR2(20)');
  add_col('EMERGENCY_CASES', 'ASSIGNED_VET_NAME', 'VARCHAR2(120)');
  add_col('EMERGENCY_CASES', 'CPR_APPROVED', 'NUMBER(1) DEFAULT 1');
  add_col('EMERGENCY_CASES', 'ESTIMATE_SIGNED', 'NUMBER(1) DEFAULT 0');
  add_col('EMERGENCY_CASES', 'DEPOSIT_PAID', 'NUMBER(1) DEFAULT 0');
  add_col('EMERGENCY_CASES', 'ARRIVAL_TIME', 'TIMESTAMP DEFAULT SYSTIMESTAMP');
END;
/

-- 2. Create EMERGENCY_CAGES table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE emergency_cages (
      cage_id VARCHAR2(20) PRIMARY KEY,
      cage_type VARCHAR2(20) NOT NULL,
      status VARCHAR2(20) DEFAULT ''empty'' NOT NULL,
      emergency_id NUMBER REFERENCES emergency_cases(emergency_id) ON DELETE SET NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF; -- ignore table already exists
END;
/

-- Seed standard 8 cages if empty
DECLARE
  v_c_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_c_count FROM emergency_cages;
  IF v_c_count = 0 THEN
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('ICU-01', 'icu', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('ICU-02', 'icu', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('ICU-03', 'icu', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('ISO-01', 'isolation', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('ISO-02', 'isolation', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('GEN-01', 'general', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('GEN-02', 'general', 'empty');
    INSERT INTO emergency_cages (cage_id, cage_type, status) VALUES ('GEN-03', 'general', 'empty');
    COMMIT;
  END IF;
END;
/

-- 3. Create EMERGENCY_FLOWSHEET table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE emergency_flowsheet (
      flowsheet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      emergency_id NUMBER NOT NULL REFERENCES emergency_cases(emergency_id) ON DELETE CASCADE,
      time_label VARCHAR2(30) NOT NULL,
      vitals_checked NUMBER(1) DEFAULT 0 NOT NULL,
      fluids_checked NUMBER(1) DEFAULT 0 NOT NULL,
      meds_checked NUMBER(1) DEFAULT 0 NOT NULL,
      notes VARCHAR2(1000),
      recorded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4. Create EMERGENCY_STAT_ORDERS table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE emergency_stat_orders (
      order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      emergency_id NUMBER NOT NULL REFERENCES emergency_cases(emergency_id) ON DELETE CASCADE,
      order_type VARCHAR2(30) NOT NULL,
      description VARCHAR2(500) NOT NULL,
      order_time VARCHAR2(30) NOT NULL,
      is_done NUMBER(1) DEFAULT 0 NOT NULL,
      completed_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
