-- ============================================
-- PAYROLL_RECORDS TABLE & SEED DATA
-- Tracks clinic staff payroll, allowances, tax, SSNIT,
-- bank loan capacity, insurance, and payment statuses
-- ============================================

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'PAYROLL_RECORDS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE payroll_records (
        payroll_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        staff_id NUMBER NOT NULL,
        user_id NUMBER NOT NULL,
        pay_period VARCHAR2(20) NOT NULL,
        basic_salary NUMBER(12,2) DEFAULT 0 NOT NULL,
        housing_allowance NUMBER(12,2) DEFAULT 0 NOT NULL,
        transport_allowance NUMBER(12,2) DEFAULT 0 NOT NULL,
        other_allowances NUMBER(12,2) DEFAULT 0 NOT NULL,
        gross_salary NUMBER(12,2) DEFAULT 0 NOT NULL,
        tax_deduction NUMBER(12,2) DEFAULT 0 NOT NULL,
        ssnit_deduction NUMBER(12,2) DEFAULT 0 NOT NULL,
        other_deductions NUMBER(12,2) DEFAULT 0 NOT NULL,
        net_salary NUMBER(12,2) DEFAULT 0 NOT NULL,
        max_loan NUMBER(12,2) DEFAULT 0 NOT NULL,
        insurance_tier VARCHAR2(50) DEFAULT ''Gold Cover'' NOT NULL,
        insurance_premium NUMBER(12,2) DEFAULT 0 NOT NULL,
        employer_insurance NUMBER(12,2) DEFAULT 0 NOT NULL,
        employee_insurance NUMBER(12,2) DEFAULT 0 NOT NULL,
        payment_status VARCHAR2(30) DEFAULT ''Paid'' NOT NULL,
        payment_date DATE DEFAULT SYSDATE,
        payment_method VARCHAR2(50) DEFAULT ''Bank Transfer'',
        notes VARCHAR2(500),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    ';
  END IF;
END;
/

-- Indexes for efficient lookups
DECLARE
  PROCEDURE add_idx(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = UPPER(p_name);
    IF v_cnt = 0 THEN
      BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX ' || p_name || ' ON ' || p_sql;
      EXCEPTION WHEN OTHERS THEN NULL;
      END;
    END IF;
  END;
BEGIN
  add_idx('IDX_PAYROLL_STAFF', 'payroll_records(staff_id)');
  add_idx('IDX_PAYROLL_USER', 'payroll_records(user_id)');
  add_idx('IDX_PAYROLL_PERIOD', 'payroll_records(pay_period)');
  add_idx('IDX_PAYROLL_STATUS', 'payroll_records(payment_status)');
END;
/

-- Populate or update payroll records for existing staff across recent periods
DECLARE
  CURSOR c_staff IS
    SELECT s.staff_id, s.user_id, s.salary, s.department, s.job_title, u.role
    FROM staff s
    JOIN users u ON u.user_id = s.user_id;

  TYPE t_periods IS VARRAY(3) OF VARCHAR2(20);
  v_periods t_periods := t_periods('2026-09-01', '2026-08-01', '2026-07-01');

  v_basic NUMBER(12,2);
  v_housing NUMBER(12,2);
  v_transport NUMBER(12,2);
  v_gross NUMBER(12,2);
  v_tax NUMBER(12,2);
  v_ssnit NUMBER(12,2);
  v_net NUMBER(12,2);
  v_loan NUMBER(12,2);
  v_tier VARCHAR2(50);
  v_premium NUMBER(12,2);
  v_er_ins NUMBER(12,2);
  v_ee_ins NUMBER(12,2);
  v_status VARCHAR2(30);
  v_cnt NUMBER;
BEGIN
  FOR r IN c_staff LOOP
    v_basic := NVL(r.salary, 6000);
    IF v_basic <= 0 THEN
      IF r.role = 'Super Admin' THEN v_basic := 14000;
      ELSIF r.role = 'Veterinarian' THEN v_basic := 9500;
      ELSIF r.role = 'Accountant' THEN v_basic := 7500;
      ELSIF r.role = 'InventoryManager' THEN v_basic := 6000;
      ELSIF r.role = 'Receptionist' THEN v_basic := 4500;
      ELSIF r.role = 'Technician' THEN v_basic := 5000;
      ELSE v_basic := 6000;
      END IF;
    END IF;

    -- Compute standard allowances
    v_housing := ROUND(v_basic * 0.12, 2);
    v_transport := ROUND(v_basic * 0.08, 2);
    v_gross := v_basic + v_housing + v_transport;

    -- Deductions: PAYE Tax (approx 15%), SSNIT (5.5%)
    v_tax := ROUND(v_gross * 0.15, 2);
    v_ssnit := ROUND(v_basic * 0.055, 2);
    v_net := v_gross - (v_tax + v_ssnit);

    -- Max Loan (typically 3x annual net or 36x monthly net capacity * 0.4 DTI)
    v_loan := ROUND(v_net * 24, 2);

    -- Insurance Tiers
    IF v_basic >= 10000 THEN
      v_tier := 'Platinum Cover';
    ELSIF v_basic >= 6500 THEN
      v_tier := 'Gold Cover';
    ELSE
      v_tier := 'Silver Cover';
    END IF;

    -- 6% annual premium split: 4% Employer, 2% Employee
    v_premium := ROUND((v_net * 12 * 0.06) / 12, 2);
    v_er_ins := ROUND((v_net * 12 * 0.04) / 12, 2);
    v_ee_ins := ROUND((v_net * 12 * 0.02) / 12, 2);

    -- Seed for the 3 pay periods
    FOR i IN 1..v_periods.COUNT LOOP
      SELECT COUNT(*) INTO v_cnt
      FROM payroll_records
      WHERE staff_id = r.staff_id AND pay_period = v_periods(i);

      IF v_periods(i) = '2026-09-01' THEN
        v_status := 'Paid';
      ELSE
        v_status := 'Paid';
      END IF;

      IF v_cnt = 0 THEN
        INSERT INTO payroll_records (
          staff_id, user_id, pay_period, basic_salary, housing_allowance, transport_allowance, other_allowances,
          gross_salary, tax_deduction, ssnit_deduction, other_deductions, net_salary, max_loan,
          insurance_tier, insurance_premium, employer_insurance, employee_insurance,
          payment_status, payment_date, payment_method, notes, created_at
        ) VALUES (
          r.staff_id, r.user_id, v_periods(i), v_basic, v_housing, v_transport, 0,
          v_gross, v_tax, v_ssnit, 0, v_net, v_loan,
          v_tier, v_premium, v_er_ins, v_ee_ins,
          v_status, TO_DATE(v_periods(i), 'YYYY-MM-DD') + 25, 'Bank Transfer', 'Monthly Clinic Payroll', SYSTIMESTAMP
        );
      END IF;
    END LOOP;
  END LOOP;
  COMMIT;
END;
/

COMMIT;
