-- addyPets veterinary clinic Oracle schema
-- Run as the application schema owner.

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  full_name VARCHAR2(120) NOT NULL,
  license_number VARCHAR2(50) UNIQUE,
  phone VARCHAR2(30),
  role VARCHAR2(40) DEFAULT 'Veterinarian' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_name VARCHAR2(100) NOT NULL,
  pet_species VARCHAR2(50) NOT NULL,
  pet_breed VARCHAR2(100),
  pet_age VARCHAR2(30),
  sex VARCHAR2(20),
  owner_name VARCHAR2(120) NOT NULL,
  owner_phone VARCHAR2(30),
  owner_email VARCHAR2(255),
  medical_notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER REFERENCES patients(patient_id),
  pet_name VARCHAR2(100) NOT NULL,
  pet_species VARCHAR2(50),
  pet_age VARCHAR2(30),
  owner_name VARCHAR2(120) NOT NULL,
  owner_phone VARCHAR2(30),
  visit_reason VARCHAR2(255),
  service VARCHAR2(100),
  appointment_time VARCHAR2(20) NOT NULL,
  veterinarian_id NUMBER REFERENCES users(user_id),
  status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT appointments_status_ck CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled'))
);

CREATE TABLE contact_form (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  pet_breed VARCHAR2(100),
  email VARCHAR2(255) NOT NULL,
  customer_questions CLOB NOT NULL,
  ip_address VARCHAR2(64),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status VARCHAR2(20) DEFAULT 'Unread' NOT NULL
);

CREATE TABLE billing (
  billing_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER REFERENCES patients(patient_id),
  appointment_id NUMBER REFERENCES appointments(appointment_id),
  amount NUMBER(12,2) DEFAULT 0 NOT NULL,
  status VARCHAR2(20) DEFAULT 'Unpaid' NOT NULL,
  description VARCHAR2(255),
  payment_method VARCHAR2(40),
  issued_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  paid_at TIMESTAMP
);

CREATE TABLE inventory (
  inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name VARCHAR2(150) NOT NULL,
  category VARCHAR2(80),
  quantity NUMBER(10,2) DEFAULT 0 NOT NULL,
  reorder_level NUMBER(10,2) DEFAULT 0 NOT NULL,
  unit_cost NUMBER(12,2) DEFAULT 0 NOT NULL,
  supplier VARCHAR2(150),
  expiry_date DATE,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE staff (
  staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER REFERENCES users(user_id),
  staff_number VARCHAR2(40) UNIQUE,
  full_name VARCHAR2(120) NOT NULL,
  department VARCHAR2(80),
  job_title VARCHAR2(80),
  phone VARCHAR2(30),
  email VARCHAR2(255),
  status VARCHAR2(20) DEFAULT 'Active' NOT NULL,
  salary NUMBER(12,2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE emergency_cases (
  emergency_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER REFERENCES patients(patient_id),
  patient_name VARCHAR2(100) NOT NULL,
  owner_name VARCHAR2(120),
  description CLOB NOT NULL,
  priority VARCHAR2(20) DEFAULT 'Urgent' NOT NULL,
  status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
  assigned_staff_id NUMBER REFERENCES staff(staff_id),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  resolved_at TIMESTAMP
);

CREATE TABLE reports (
  report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type VARCHAR2(60) NOT NULL,
  report_month DATE,
  generated_by NUMBER REFERENCES users(user_id),
  report_data CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR2(80) NOT NULL UNIQUE,
  description VARCHAR2(255),
  permissions_json CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE clinic_settings (
  setting_key VARCHAR2(100) PRIMARY KEY,
  setting_value CLOB,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE notification_preferences (
  preference_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_key VARCHAR2(80) NOT NULL UNIQUE,
  email_enabled CHAR(1) DEFAULT 'Y' NOT NULL,
  sms_enabled CHAR(1) DEFAULT 'N' NOT NULL,
  in_app_enabled CHAR(1) DEFAULT 'Y' NOT NULL
);

CREATE INDEX appointments_time_ix ON appointments(appointment_time);
CREATE INDEX appointments_status_ix ON appointments(status);
CREATE INDEX patients_owner_phone_ix ON patients(owner_phone);
CREATE INDEX emergency_status_ix ON emergency_cases(status);
CREATE INDEX contact_form_status_ix ON contact_form(status);

COMMIT;
