-- addyPets veterinary clinic Oracle schema
-- Run as the application schema owner.

-- ============================================
-- USERS TABLE (Personal & Authentication Info)
-- ============================================
CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  full_name VARCHAR2(120) NOT NULL,
  phone VARCHAR2(30),
  role VARCHAR2(50) DEFAULT 'Veterinarian' NOT NULL,
  status VARCHAR2(20) DEFAULT 'Active' NOT NULL,
  profile_image CLOB,
  password_reset_token_hash VARCHAR2(64),
  password_reset_expires_at TIMESTAMP,
  last_login TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT users_status_ck CHECK (status IN ('Active', 'Inactive', 'Suspended', 'Pending'))
);

-- ============================================
-- PATIENTS TABLE
-- ============================================
CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_number VARCHAR2(20) UNIQUE,
  pet_name VARCHAR2(100) NOT NULL,
  pet_species VARCHAR2(50) NOT NULL,
  pet_breed VARCHAR2(100),
  pet_age VARCHAR2(30),
  pet_age_value NUMBER(3),
  pet_age_unit VARCHAR2(10),
  sex VARCHAR2(20),
  owner_name VARCHAR2(120) NOT NULL,
  owner_phone VARCHAR2(30),
  owner_email VARCHAR2(255),
  medical_notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================
-- APPOINTMENTS TABLE
-- ============================================
CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_number VARCHAR2(20) UNIQUE,
  patient_id NUMBER REFERENCES patients(patient_id),
  pet_name VARCHAR2(100) NOT NULL,
  pet_species VARCHAR2(50),
  pet_age VARCHAR2(30),
  pet_age_value NUMBER(3),
  pet_age_unit VARCHAR2(10),
  owner_name VARCHAR2(120) NOT NULL,
  owner_phone VARCHAR2(30),
  visit_reason VARCHAR2(255),
  service VARCHAR2(100),
  appointment_time VARCHAR2(20) NOT NULL,
  veterinarian_id NUMBER REFERENCES users(user_id),
  status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT appointments_status_ck CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled'))
);

-- Triggers for auto-generating human readable numbers
CREATE OR REPLACE TRIGGER patient_number_from_id
FOR INSERT ON patients
COMPOUND TRIGGER
  patient_ids SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
  AFTER EACH ROW IS
  BEGIN
    patient_ids.EXTEND;
    patient_ids(patient_ids.COUNT) := :NEW.patient_id;
  END AFTER EACH ROW;
  AFTER STATEMENT IS
  BEGIN
    UPDATE patients
    SET patient_number = 'PAT-' || LPAD(TO_CHAR(patient_id), 4, '0')
    WHERE patient_id IN (SELECT COLUMN_VALUE FROM TABLE(patient_ids));
  END AFTER STATEMENT;
END;
/

CREATE OR REPLACE TRIGGER appointment_number_from_id
FOR INSERT ON appointments
COMPOUND TRIGGER
  appointment_ids SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
  AFTER EACH ROW IS
  BEGIN
    appointment_ids.EXTEND;
    appointment_ids(appointment_ids.COUNT) := :NEW.appointment_id;
  END AFTER EACH ROW;
  AFTER STATEMENT IS
  BEGIN
    UPDATE appointments
    SET appointment_number = 'APT-' || LPAD(TO_CHAR(appointment_id), 4, '0')
    WHERE appointment_id IN (SELECT COLUMN_VALUE FROM TABLE(appointment_ids));
  END AFTER STATEMENT;
END;
/

-- ============================================
-- CONTACT FORM
-- ============================================
CREATE TABLE contact_form (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  pet_breed VARCHAR2(100),
  email VARCHAR2(255) NOT NULL,
  customer_questions CLOB NOT NULL,
  ip_address VARCHAR2(64),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================
-- BILLING TABLE
-- ============================================
CREATE TABLE billing (
  billing_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER REFERENCES patients(patient_id),
  appointment_id NUMBER REFERENCES appointments(appointment_id),
  amount NUMBER(12,2) DEFAULT 0 NOT NULL,
  status VARCHAR2(20) DEFAULT 'Unpaid' NOT NULL,
  description VARCHAR2(255),
  payment_method VARCHAR2(40),
  issued_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  paid_at TIMESTAMP
);

-- ============================================
-- INVENTORY TABLE
-- ============================================
CREATE TABLE inventory (
  inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name VARCHAR2(150) NOT NULL,
  category VARCHAR2(80),
  quantity NUMBER(10,2) DEFAULT 0 NOT NULL,
  reorder_level NUMBER(10,2) DEFAULT 0 NOT NULL,
  unit_cost NUMBER(12,2) DEFAULT 0 NOT NULL,
  supplier VARCHAR2(150),
  expiry_date DATE,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================
-- STAFF TABLE (Employment & Professional Info)
-- ============================================
CREATE TABLE staff (
  staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
  staff_number VARCHAR2(40) UNIQUE,
  license_number VARCHAR2(100),
  department VARCHAR2(80),
  job_title VARCHAR2(80),
  salary NUMBER(12,2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER staff_number_from_id
FOR INSERT ON staff
COMPOUND TRIGGER
  staff_ids SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();

  AFTER EACH ROW IS
  BEGIN
    staff_ids.EXTEND;
    staff_ids(staff_ids.COUNT) := :NEW.staff_id;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
  BEGIN
    UPDATE staff
    SET staff_number = CASE
      WHEN LOWER(NVL(job_title, '')) LIKE '%technician%' THEN 'TECH-'
      WHEN LOWER(NVL(job_title, '')) LIKE '%vet%'
        OR LOWER(NVL(job_title, '')) LIKE '%veterinarian%'
        OR LOWER(NVL(job_title, '')) LIKE '%surgeon%' THEN 'DOC-'
      WHEN LOWER(NVL(job_title, '')) LIKE '%reception%' THEN 'REC-'
      WHEN LOWER(NVL(job_title, '')) LIKE '%account%'
        OR LOWER(NVL(department, '')) LIKE '%finance%' THEN 'ACC-'
      WHEN LOWER(NVL(job_title, '')) LIKE '%inventory%' THEN 'INV-'
      ELSE 'STF-'
    END || LPAD(TO_CHAR(staff_id), 4, '0')
    WHERE staff_id IN (SELECT COLUMN_VALUE FROM TABLE(staff_ids));
  END AFTER STATEMENT;
END;
/

-- ============================================
-- DOCTOR AVAILABILITY
-- ============================================
CREATE TABLE doctor_availability (
  availability_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id NUMBER NOT NULL UNIQUE REFERENCES staff(staff_id) ON DELETE CASCADE,
  availability_status VARCHAR2(20) DEFAULT 'Available' NOT NULL,
  start_time VARCHAR2(5),
  end_time VARCHAR2(5),
  leave_reason VARCHAR2(255),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT doctor_availability_status_ck
    CHECK (availability_status IN ('Available', 'Unavailable', 'On Leave'))
);

-- ============================================
-- RECURRING BLOCKS
-- ============================================
CREATE TABLE recurring_blocks (
  block_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(120) NOT NULL,
  days_of_week VARCHAR2(30) NOT NULL,
  start_time VARCHAR2(5) NOT NULL,
  end_time VARCHAR2(5) NOT NULL,
  icon VARCHAR2(50),
  is_active CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT recurring_blocks_active_ck CHECK (is_active IN ('Y', 'N'))
);

-- ============================================
-- EMERGENCY CASES
-- ============================================
CREATE TABLE emergency_cases (
  emergency_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL REFERENCES patients(patient_id),
  description CLOB NOT NULL,
  priority VARCHAR2(20) DEFAULT 'Urgent' NOT NULL,
  status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
  assigned_staff_id NUMBER REFERENCES staff(staff_id),
  source VARCHAR2(30) DEFAULT 'website' NOT NULL,
  ai_reasoning CLOB,
  arrival_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  resolved_at TIMESTAMP
);

CREATE TABLE emergency_case_tags (
  emergency_id NUMBER NOT NULL REFERENCES emergency_cases(emergency_id) ON DELETE CASCADE,
  tag VARCHAR2(80) NOT NULL,
  CONSTRAINT emergency_case_tags_pk PRIMARY KEY (emergency_id, tag)
);

CREATE TABLE emergency_case_consents (
  emergency_id NUMBER NOT NULL REFERENCES emergency_cases(emergency_id) ON DELETE CASCADE,
  consent_type VARCHAR2(30) NOT NULL,
  is_approved NUMBER(1) DEFAULT 0 NOT NULL,
  recorded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT emergency_case_consents_pk PRIMARY KEY (emergency_id, consent_type),
  CONSTRAINT emergency_case_consents_type_ck CHECK (consent_type IN ('CPR', 'ESTIMATE', 'DEPOSIT')),
  CONSTRAINT emergency_case_consents_approved_ck CHECK (is_approved IN (0, 1))
);

-- ============================================
-- REPORTS
-- ============================================
CREATE TABLE reports (
  report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type VARCHAR2(60) NOT NULL,
  report_month DATE,
  generated_by NUMBER REFERENCES users(user_id),
  report_data CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================
-- ROLES & PERMISSIONS
-- ============================================
CREATE TABLE roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR2(80) NOT NULL UNIQUE,
  description VARCHAR2(255),
  permissions_json CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE permissions (
  permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource VARCHAR2(100) NOT NULL,
  action VARCHAR2(50) NOT NULL,
  description VARCHAR2(255),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT unique_permission UNIQUE (resource, action)
);

CREATE TABLE role_permissions (
  role_permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id NUMBER REFERENCES roles(role_id) ON DELETE CASCADE,
  permission_id NUMBER REFERENCES permissions(permission_id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT unique_role_permission UNIQUE (role_id, permission_id)
);

-- ============================================
-- CLINIC SETTINGS & PREFERENCES
-- ============================================
CREATE TABLE clinic_settings (
  setting_key VARCHAR2(100) PRIMARY KEY,
  setting_value CLOB,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE notification_preferences (
  preference_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_key VARCHAR2(80) NOT NULL UNIQUE,
  email_enabled CHAR(1) DEFAULT 'Y' NOT NULL,
  sms_enabled CHAR(1) DEFAULT 'N' NOT NULL,
  in_app_enabled CHAR(1) DEFAULT 'Y' NOT NULL
);

-- ============================================
-- USER NOTIFICATIONS
-- ============================================
CREATE TABLE user_notifications (
  notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  title VARCHAR2(160) NOT NULL,
  message VARCHAR2(1000) NOT NULL,
  type VARCHAR2(30) DEFAULT 'info' NOT NULL,
  link VARCHAR2(255),
  source_id VARCHAR2(100),
  is_read CHAR(1) DEFAULT 'N' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT user_notifications_read_ck CHECK (is_read IN ('Y', 'N'))
);

-- ============================================
-- STAFF MESSAGES & DOCUMENT SHARING
-- ============================================
CREATE TABLE staff_messages (
  message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  receiver_id NUMBER REFERENCES users(user_id) ON DELETE CASCADE,
  message_text CLOB,
  attachment_data CLOB,
  attachment_name VARCHAR2(255),
  attachment_type VARCHAR2(100),
  attachment_size NUMBER,
  is_read NUMBER(1) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX appointments_time_ix ON appointments(appointment_time);
CREATE INDEX appointments_status_ix ON appointments(status);
CREATE INDEX patients_owner_phone_ix ON patients(owner_phone);
CREATE INDEX emergency_status_ix ON emergency_cases(status);
CREATE INDEX contactform_email_ix ON contact_form(email);
CREATE INDEX users_email_ix ON users(LOWER(email));
CREATE INDEX users_status_ix ON users(status);
CREATE INDEX users_last_login_ix ON users(last_login);
CREATE INDEX users_password_reset_ix ON users(password_reset_token_hash);
CREATE INDEX staff_user_id_ix ON staff(user_id);
CREATE INDEX staff_number_ix ON staff(staff_number);
CREATE INDEX user_notif_user_read_ix ON user_notifications(user_id, is_read, created_at);
CREATE INDEX staff_msg_sender_ix ON staff_messages(sender_id);
CREATE INDEX staff_msg_receiver_ix ON staff_messages(receiver_id);
CREATE INDEX staff_msg_created_ix ON staff_messages(created_at);

COMMIT;
